exclude: ^.vscode/.*|^sample2/.*|^.pre-commit-config.yaml
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # - id: no-commit-to-branch
      #   args: ["--branch", "main", "--branch", "dev"]
      - id: check-docstring-first
        # - id: check-executables-have-shebangs
        exclude: ^(.*\.lock|.*\.toml)$
      - id: check-case-conflict
      # - id: check-added-large-files
      #   exclude: ^(.*\/dummy.*|.*\.json)$
      #   args: ["--maxkb=750", "--enforce-all"]
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: ^tests/

  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        name: docformatter
        args:
          [
            -r,
            -i,
            --pre-summary-newline,
            --make-summary-multi-line,
            --wrap-summaries,
            "90",
            --wrap-descriptions,
            "90",
            app,
            tests,
          ]

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.2.0
  #   hooks:
  #     - id: ruff
  #       args: [--fix]
  #     # - id: ruff-format

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", --line-length=72]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=72]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
      - id: mypy
        args: [--strict]
        exclude: queries.py
        additional_dependencies:
          - fastapi
          - pydantic
          - types-python-jose
          - types-toml
          - types-ujson
          - types-psycopg2
          - types-pytz
          - pydantic_settings
          - loguru

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       stages: [commit]
  #       entry: pytest
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true

  #     - id: pytest-cov
  #       name: pytest
  #       stages: [push]
  #       language: system
  #       entry: pytest --cov=tests --cov-fail-under=70
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
