"""
Base Commit.

Revision ID: 226107d3f03b
Revises:
Create Date: 2024-02-12 13:45:14.601001
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "226107d3f03b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samples",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("task", sa.String(), nullable=True),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", "uuid"),
    )
    op.create_index(
        op.f("ix_samples_created_by"),
        "samples",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samples_id"), "samples", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_samples_updated_by"),
        "samples",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samples_uuid"), "samples", ["uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_samples_uuid"), table_name="samples")
    op.drop_index(op.f("ix_samples_updated_by"), table_name="samples")
    op.drop_index(op.f("ix_samples_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_created_by"), table_name="samples")
    op.drop_table("samples")
    # ### end Alembic commands ###
